version: "3.8"
services:
  mongo-goals-app:
    image: 'mongo'
    volumes:
      - data:/data/db
    # environment:
    #   name: value
    # env_file:
    #   - ./.env
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - goals-logs:/app/logs
      - ./backend:/app:ro
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo-goals-app
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src:ro
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  goals-logs: